### ISSUE TITLE
建议@单词理解的自己编辑能力

### ISSUE THREAD

**Issue by howardmi5** [waynecz/dadda-translate-crx#102]
希望能增加对单词理解的自己编辑能力.
场景:在读一些小说和帖子中加入该词到哒哒的,自己加入看到这个单词的句子,有助于回忆起当时的语境.

**Comment by waynecz** [comment]
@howardmi5 这个需求描述的有点模糊哈，你指的是单词加入生词簿时顺便添加当时的例句？

**Comment by howardmi5** [comment]
这样说了 我在一个美剧中看到这一个 词的特殊用法，在dada的自动翻译中没有或是不准确。我希望能把这个词的在这个美剧的字幕翻译和例句自己写在dada里。
这种情况经常出现 我在看到一篇文章中看到一个词，它和这篇文章有这紧密的联系。过段日子dada再跳出这个词让我复习的时候，我单凭dada给出的解释无法复原我当时如何看到这个词 在哪里看到这个词的。这个记忆宫殿 有点像。和人类的记忆原理有点关系。eg 回忆一个句子 比回忆一个词 容易的多。

**Comment by waynecz** [comment]
有点理解你的意思了，那么达达如果有这样一个功能：
1. 划中某个单词
2. 摁一组快捷键，弹出一个弹窗
3. 单词是这个单词，但是会多出一个输入框让你填例句
4. 确认后添加至生词簿，并且后面弹出的吐司的内容里包含你自己填的例句

你看这样是否能满足
ps：你现在吐司弹词可以用了吗
