### ISSUE TITLE
谷歌商店里没有达达划词翻译了吗？添加扩展无法使用

### ISSUE THREAD

**Issue by JaysonRoom** [waynecz/dadda-translate-crx#103]
谷歌商店里没有达达划词翻译了吗？添加扩展无法使用

**Comment by waynecz** [comment]
[ 达达翻译 google stroe](https://chrome.google.com/webstore/detail/%E8%BE%BE%E8%BE%BE%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cajhcjfcodjoalmhjekljnfkgjlkeajl) 试试这个
