### ISSUE TITLE
你好，用了你的扩展对我很有帮助

### ISSUE THREAD

**Issue by cyandee** [waynecz/dadda-translate-crx#109]
就是有一个建议希望你能考虑一下，就是浏览器提醒单词的时候，有些单词我忘记了，点进去发现是搜狗翻译，但是我觉得搜狗翻译真的挺烂的，能不能在这个功能上加个自定义功能，可以用谷歌或者有道之类的

**Comment by waynecz** [comment]
2.0 正在开发其他翻译引擎的支持

**Comment by cyandee** [comment]
感谢！

Black Wayne <notifications@github.com> 于2018年9月25日周二 上午11:09写道：
