### ISSUE TITLE
某些页面无法使用此插件，比如github....

### ISSUE THREAD

**Issue by strongcode9527** [waynecz/dadda-translate-crx#112]
如题

**Comment by inerversleep** [comment]
github我的正常，目前没遇过哪个页面不能用的。最新版chrome

**Comment by waynecz** [comment]
是指出不来翻译框还是指无法发音？

**Comment by strongcode9527** [comment]
@waynecz 双击单词之后，无法显示翻译框。macos ， 最新版的chrome

**Comment by strongcode9527** [comment]
@waynecz 我找到原因了，是因为和一个查看github仓库的插件冲突了，只要把内个插件卸载掉，就可以用了。谢谢

**Comment by waynecz** [comment]
可以问下是什么插件吗？我排查下看能不能解决

**Comment by strongcode9527** [comment]
@waynecz [gayhub的仓库链接](https://github.com/jawil/GayHub)

**Comment by pilileishen** [comment]
翻译大片的英文，看不到下半部分。

**Comment by Ehco1996** [comment]
@waynecz 
gitbook页面 翻译框也弹不出来

**Comment by waynecz** [comment]
@Ehco1996 可以给个示例页面的链接不

**Comment by Aoerz** [comment]
[这个网站也无法用](https://www.windowscentral.com/)
