### ISSUE TITLE
win10 下 alt+tab 进行切换的时候出现弹窗且无法关闭

### ISSUE THREAD

**Issue by shanyuhai123** [waynecz/dadda-translate-crx#113]
![image](https://user-images.githubusercontent.com/27122409/47155610-b0e05300-d317-11e8-829c-09384a470d8f.png)

**Comment by shanyuhai123** [comment]
我这边并没有开启 alt 翻译的选项

**Comment by gegehennb** [comment]
win10 64位2016ltsb，浏览器是cent 3.5.3.50（正式版本） （32 位） (Chromium 67.0.3396.99)
未出现此问题
但是出现了另外的问题，弹窗出现后按ctrl+enter没有任何反应，以及快按3下alt出现go图标不怎么好用，经常性按不出来，可能是我的姿势有问题？？
反馈问题之余，感谢大佬这么好的扩展

**Comment by waynecz** [comment]
我的锅，明天我再改下交互，有什么推荐的或者说你们认为爱恋自然的方式吗

**Comment by panda331** [comment]
我刚想发，我的情况是上述两种之和
alt+tab应该是触发了按tab开启窗口，按esc可隐藏；输入之后无论是按ctrl+enter还是win+enter都毫无反应

**Comment by panda331** [comment]
试了下又发现，按alt呼出窗口后，不是直接就能输入的（光标会闪一下然后消失），按esc一次出现光标可输入，再按一次光标再消失，还要再按一次esc窗口才关闭。
我的天

**Comment by cipchk** [comment]
建议优先此理它，因为它已经严重影响我的使用体验了。

**Comment by ppambler** [comment]
每次alt+tab就弹出个窗口，这使用体验很不好啊！这个在本地下载了个有道词典，自定义快捷键，就可以做到这个功能了啊

**Comment by xfhy** [comment]
我觉得可以搞一个快捷键弹出那个窗口比较好,,,昨晚我疯狂切换程序时,那个窗口疯狂弹出,,谢谢作者,麻烦你了,辛苦了

**Comment by waynecz** [comment]
@kanong017 @anbeibei1024  @Ryanhui @gazerhuang @ xfhy 
目前正在更改这个逻辑中，打算添加开关 并且 将快捷键改为 alt + shift + d 的形式，大家觉得可行不

**Comment by waynecz** [comment]
@gegehennb 这个快捷键怎么设置？求

**Comment by Kanong017** [comment]
我觉得OK

**Comment by cipchk** [comment]
@waynecz 可选功能最好了。我想用这个会有大量的IT从业者，dada 的需求是在于google时可以查阅一些不太读得懂的语句。真心建议越简单越好，其他需求都放入可选功能里面。

> PS： 我已经暂时切换回划词翻译插件。

**Comment by Ryanhui** [comment]
无论如何tab+alt切换不弹框就好了

**Comment by Kanong017** [comment]
@waynecz 而且!反馈入口不太好找啊!!要么加一个入口!!!要么搞个TG或者QQ群!!!!

**Comment by gegehennb** [comment]
> @gegehennb 这个快捷键怎么设置？求

应该是在这个页面下;chrome://extensions/shortcuts
[https://i.loli.net/2018/10/19/5bc94bd23ecf6.jpg
](url)
此时我就将扩展的激活快捷键设置为了alt+q
按下这个快捷键就可以激活扩展界面

**Comment by waynecz** [comment]
@kanong017 @anbeibei1024  @Ryanhui @gazerhuang @ xfhy 以及大家

谢谢大家的即时反馈，[v1.1.13-release](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.13) 已经更新，**稍稍*不反人类了，这次是我在做功能的时候没考虑到平台差别，莽了，对不起了。

本来这两个小功能是准备写在正在做的 2.0 版本里的，但是想到这应该能提升不少效率（个人认为）就打算先出个简单的版本在当前版本下，没想到 G 了😂。

给了我个警钟，目前规划中很多新功能须要想办法和用户讨论，方式将像 @Kanong017 说的一样建个群

最后还是谢谢大家，给大佬们倒茶☕️

**Comment by waynecz** [comment]
@cipchk 哈哈哈划词翻译插件的作者就坐在我对面☺️

**Comment by shetz163** [comment]
十分感谢更新   只是更新后的框里还是无法用ctrl+enter来触发翻译(系统是windwos10)

**Comment by eartooth** [comment]
> 十分感谢更新 只是更新后的框里还是无法用ctrl+enter来触发翻译(系统是windwos10)

**Comment by gegehennb** [comment]
@waynecz  win10下win+enter 会弹出系统的那个讲述人。。。。
![snipaste_2018-10-19_18-39-12](https://user-images.githubusercontent.com/16933365/47213678-4ccc9600-d3ce-11e8-9236-855947a6d8f9.jpg)

**Comment by waynecz** [comment]
哭了，我再改下，ctrl + enter 有坑吗？ @gegehennb

**Comment by gegehennb** [comment]
@waynecz  我这里是正常的，不排除其他人有什么程序或者阔珍占用了这个键233333

**Comment by gegehennb** [comment]
@waynecz 我觉得可以尝试点击右边小猫触发的机制吧23333

**Comment by waynecz** [comment]
@gegehennb 我原本的目标是不按一下鼠标达成翻译的目的，一种方法是做成输入完自动翻译然后展示成列表的形式，但是工作量有点大，就先暂时做成翻译结果弹窗了，然后就有了如何触发翻译的问题，emmmm，还有种方式是子弟定义快捷键，但也要写挺多的，打算放在2.0一起写掉，那先暂时弄成点击图标或者输入完成 0.几 秒后自动翻译吧

**Comment by waynecz** [comment]
新建了个 [Telegram](https://t.me/joinchat/HZtwHQyv_GqSKmyXr_7reA) 群，欢迎大家加入讨论

或者直接搜索 「达达翻译」
