### ISSUE TITLE
如何关闭 type something？

### ISSUE THREAD

**Issue by cipchk** [waynecz/dadda-translate-crx#114]
![tim 20181018214410](https://user-images.githubusercontent.com/2987467/47158790-f8b6a880-d31e-11e8-8bd1-a4974fb49035.png)

在设置已经关闭所有选项，但依然动不动就出现。

> 非常感谢提供这么好用的功能，但我只想要简简单单的东西。

**Comment by waynecz** [comment]
我的锅，明天会设置开关，或者直接去掉

**Comment by cipchk** [comment]
谢谢，刚看到有好多人发布 issues，我关掉这个 issues。
