### ISSUE TITLE
按Alt键翻译的设置失效

### ISSUE THREAD

**Issue by inerversleep** [waynecz/dadda-translate-crx#115]
现在只要选到就翻译，不管是否开启按ALT键翻译的功能
1.1.11

**Comment by waynecz** [comment]
是不是打开了直接翻译模式，就是插件图标旁边有go字样
![image](https://user-images.githubusercontent.com/11238540/47195239-98128480-d38d-11e8-97ee-dd7054c55563.png)

**Comment by waynecz** [comment]
[v1.1.13](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.13) 改了快捷键，现在不会出现闪烁的状态了，望更新，笔芯
