### ISSUE TITLE
切换程序必出现,alt 0.5秒出现的对话框

### ISSUE THREAD

**Issue by xfhy** [waynecz/dadda-translate-crx#116]
强烈建议,取消alt 0.5秒出现的对话框.每次从浏览器切到其他程序,那个对话框必然会出现.很尴尬...每次都要按ESC去取消,严重影响了用户体验..

**Comment by gazerhuang** [comment]
赞同，建议加个单独的开关，我习惯按一下Alt翻译，但是用Alt+Tab切换程序触发真是太烦了，我自己常用其他Alt组合键也会触发，已经是干扰到我正常使用了……顺带一提，不管是页面上提示的Ctrl+Enter还是更新说明里的Win+Enter，都没办法翻译啊……

**Comment by Ryanhui** [comment]
同样问题+1 alt+tab键切换后出现Type someth的对话框

**Comment by anbeibei1024** [comment]
同样问题 +1 怎样去掉啊 设置里明明没有打开啊 好烦

**Comment by Kanong017** [comment]
附议..这个功能虽然好..但逻辑不对啊

**Comment by waynecz** [comment]
正在取消取消中，目前打算添加开关、将快捷键改为 alt + shift + d 的形式，大家觉得可行不

**Comment by waynecz** [comment]
讨论移至 #113 这里暂时关闭
