### ISSUE TITLE
打开go模式后无法关闭

### ISSUE THREAD

**Issue by DirtyBat** [waynecz/dadda-translate-crx#117]
早上发现了更新，按照说明连按了3下alt没有开启go模式，改成长按之后不但呼出了打字框也开启了go模式，然后go模式始终无法关闭，一直处于选中就翻译的情况。
系统win10，chrome版本为最新。

**Comment by DirtyBat** [comment]
成功关闭。我发现长按alt之后右上角的“go”图标不断闪烁，猜测处于快速开关状态，碰了碰运气及时松手，就关了。

**Comment by waynecz** [comment]
今天会改掉逻辑，换用快捷键方式，目前打算用 alt + shift + g

**Comment by waynecz** [comment]
[v1.1.13](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.13) 改了快捷键，现在不会出现闪烁的状态了，望更新，笔芯
