### ISSUE TITLE
macos 下 alt 键 的功能开关

### ISSUE THREAD

**Issue by msongz** [waynecz/dadda-translate-crx#119]
希望可以有设置可以关闭 alt 键的功能
因为我 alt 键是截图的快捷键
按短时间也会出现输入框
想关闭之，貌似没找到关闭选项
希望作者考虑下
谢谢

**Comment by timfei** [comment]
同样的，我的 Alt 长按有其他功能，总是会呼出显示，希望作者能在设置里有个选项让人关闭。
谢谢了。

**Comment by abel533** [comment]
反馈的真快。。alt确实反人类。

**Comment by waynecz** [comment]
@abel533 😂因为我用 mac 的原因惯性思维了，下个大版本整理交互
