### ISSUE TITLE
有一个问题反馈一下

### ISSUE THREAD

**Issue by bigbigbo** [waynecz/dadda-translate-crx#12]
![qq 20180409104650](https://user-images.githubusercontent.com/19587016/38477109-a0a6c5bc-3be3-11e8-9d60-659d215492c0.png)

我开启了直接翻译，但是当在编辑器中，我还未选中任何内容，也是会有弹窗出来，这点应该可以优化下。

**Comment by waynecz** [comment]
直接使用辞典可以在[问卷调查](https://github.com/waynecz/dadda-translate-crx/issues/11)这里填一下？

**Comment by bigbigbo** [comment]
@waynecz 问卷中好像有人提了
---
:clock8: 设置页添加手动翻译输入框

**Comment by waynecz** [comment]
恩恩是有人提，那个问卷是个统计作用，就是看有多少人提
