### ISSUE TITLE
始终提示“无释义”

### ISSUE THREAD

**Issue by Utaha** [waynecz/dadda-translate-crx#125]
查询任意词语均提示“无释义”
Chrome 商店版，Windows 10 1809， Cent Browser (Chromium 69.0.3497.100)

**Comment by waynecz** [comment]
可能是搜狗上新的API了，我明天看下

**Comment by paohulong** [comment]
同，我也是这样。昨天还是正常的

**Comment by Twor** [comment]
双11可能要加班吧！

**Comment by zhaorengui** [comment]
遇到同样问题

**Comment by kesai** [comment]
请尽快解决哦，等着用呢

**Comment by kesai** [comment]
请尽快解决哦，等着用呢

**Comment by waynecz** [comment]
各位，接口暂时已经修复    

修复版本： v1.1.15

**Comment by Oldmoooon** [comment]
👍🏻

**Comment by waynecz** [comment]
新建了个 [Telgram](https://t.me/joinchat/HZtwHQyv_GqSKmyXr_7reA) 群，欢迎大家加入讨论

或者直接搜索 「达达翻译」
