### ISSUE TITLE
翻译单词或句子显示无释义

### ISSUE THREAD

**Issue by BenjaminGao** [waynecz/dadda-translate-crx#126]
RT。
不知道是不是搜狗的对外 API 的问题，不过我去搜狗网页端去看了下，没什么问题。

**Comment by BenjaminGao** [comment]
> RT。
> 不知道是不是搜狗的对外 API 的问题，不过我去搜狗网页端去看了下，没什么问题。

问题重复了，请关闭 issus。

**Comment by waynecz** [comment]
#125
