### ISSUE TITLE
滑词翻译狗带了？

### ISSUE THREAD

**Issue by iYting** [waynecz/dadda-translate-crx#129]
**滑词翻译狗带了？**
滑词翻译功能是取消了吗？ 为什么我的不能滑词翻译了。

**Comment by waynecz** [comment]
（诶？我这是正常的

可以说一下浏览器版本，失效页面，插件版本吗

**Comment by wanyaoqi** [comment]
@waynecz 你好
chrome 版本 70.0.3538.102（正式版本） （64 位）
单个单词翻译可用，句子翻译无释义

**Comment by waynecz** [comment]
@wanyaoqi @iYting v1.1.16 修复了_(:зゝ∠)_

**Comment by wanyaoqi** [comment]
@waynecz  很多情况下选多了一些单词会翻译错误，之前好像是不会的，这种问题能修复吗
![image](https://user-images.githubusercontent.com/18528551/48965137-9ffbbf00-eff2-11e8-8128-127f4b18b607.png)
