### ISSUE TITLE
安全问题，划词后立即连接搜狗服务器，此时并没有点击翻译按钮

### ISSUE THREAD

**Issue by barrer** [waynecz/dadda-translate-crx#13]
正常是点击翻译按钮再连接服务器，目前会导致本来不打算翻译的内容，由于选取自动发送到搜狗服务器了

**Comment by waynecz** [comment]
对的，本来为了解决的问题是点击翻译后采取翻译会导致面板出来有延迟，所以选择了预翻译的模式，这里的安全问题是指？

**Comment by chaos-nihilo** [comment]
主要是隐私问题, 每一次选取内容都会被发送到搜狗, 里面可能会有敏感或者隐私数据

**Comment by waynecz** [comment]
@nihilox 这个问题这里 V 友有讨论 https://www.v2ex.com/t/445584
