### ISSUE TITLE
vue的英文文档页面用不了

### ISSUE THREAD

**Issue by Alan18725158720** [waynecz/dadda-translate-crx#130]
vue的英文文档页面用不了，win10,Dadda-生词薄，chrome版本 70.0.3538.102（正式版本） （64 位）

**Comment by waynecz** [comment]
![image](https://user-images.githubusercontent.com/11238540/48750031-4fb1f380-ecb8-11e8-84da-8be03dc7df90.png)

可以打开检查器看下有没有这个 dom 插入吗

**Comment by waynecz** [comment]
暂时先关闭了，如果有后续问题可以继续开哦
