### ISSUE TITLE
能否支持Chrome打开本地HTML或PDF翻译？

### ISSUE THREAD

**Issue by shiwenwang** [waynecz/dadda-translate-crx#136]

**Comment by imcsq** [comment]
同求！期待成为看论文的神器呀~ 感觉会比有道什么的好用

**Comment by waynecz** [comment]
😖 尽力，四月份开始更新

**Comment by JingchengLi** [comment]
同求这个功能呀，赞作者开发出这么好的扩展 @waynecz

**Comment by JingchengLi** [comment]
勾选“允许访问文件网址”之后可以了，但是有个问题：在本地pdf的 使用上没有像在普通网页上那么方便，翻译完的内容会一直显示在左上角没法隐藏，再次划词后不会显示达达的图标，只能通过右键菜单来选择。

**Comment by shiwenwang** [comment]
当前浏览器外划词功能已经非常好用。该问题将关闭。
