### ISSUE TITLE
页面内输入框不能正常使用

### ISSUE THREAD

**Issue by vaguest** [waynecz/dadda-translate-crx#137]
在页面内使用Alt+shift+D呼出的页面内搜索，输入单词后，按ctrl+enter并没有进行翻译。
![snipaste_2018-11-24_14-57-07](https://user-images.githubusercontent.com/34848126/48965501-8742d780-eff9-11e8-9dba-234a0ef63429.png)

**Comment by vaguest** [comment]
同时希望在扩展程序这里添加翻译中文，或者显示输入英语的读音。
![snipaste_2018-11-24_15-00-50](https://user-images.githubusercontent.com/34848126/48965517-cc670980-eff9-11e8-8bf1-14650ac5e6b1.png)

**Comment by vaguest** [comment]
最后万分感谢开发人员的辛勤工作，这只是我个人的小小建议。同时希望能开放赞助感谢通道。

**Comment by waynecz** [comment]
因为最近忙其他事情去了，新功能更新频率会下来，你这边建议的功能很棒，已考虑加入到 2.0 版本的开发中:
+ 到时页面翻译框将会增强，翻译结果会详细的展示不需要按 ctrl + enter;
+ 扩展程序那里也会展示尽可能和页面内翻译结果差不多的内容；

另外目前 1.x 版本暂时不会增加额外的功能了，可能需要大家等一段时间_(:зゝ∠)_~赞助就不需要啦，本来最开始做就是给自己用的哈哈

**Comment by waynecz** [comment]
issue 暂时先关闭，不过可以继续在这里讨论，或者大佬有Telegram 的话可以进群哦

**Comment by whyAtGh** [comment]
同样的问题。ctrl+enter快捷键没有反应。
新版本会不会更新呢？
