### ISSUE TITLE
能否增加自定义域名白名单列表

### ISSUE THREAD

**Issue by yjiaz** [waynecz/dadda-translate-crx#158]
在使用石墨文档时，翻译插件总是会弹出，影响到使用。能否增加自定义名单，使插件不在一些域名下被启用，谢谢！
![image](https://ws4.sinaimg.cn/large/005GRCB4ly1fzahj7v7w2j30b906dt8r.jpg)

**Comment by waynecz** [comment]
![image](https://user-images.githubusercontent.com/11238540/51363167-bebd9400-1b11-11e9-8ca0-843874b2c8b3.png)

可以尝试将石墨加入黑名单

**Comment by yjiaz** [comment]
> ![image](https://user-images.githubusercontent.com/11238540/51363167-bebd9400-1b11-11e9-8ca0-843874b2c8b3.png)
> 
> 可以尝试将石墨加入黑名单

啊抱歉，我一直右键进设置的，所以没看到这个选项，麻烦了...
