### ISSUE TITLE
不翻译纯中文这个功能应该同时也忽略标点符号

### ISSUE THREAD

**Issue by demohi** [waynecz/dadda-translate-crx#16]

**Comment by ciknight** [comment]
逗号和句号是没有问题的，但是冒号和书名号并没有被排除。

**Comment by demohi** [comment]
```
// 这个把中文和常见中文字符都包含了
/[\u4e00-\u9fa5|\u3002|\uff1f|\uff01|\uff0c|\u3001|\uff1b|\uff1a|\u201c|\u201d]/
```

**Comment by ciknight** [comment]
@demohi 

`『』「」﹃﹄〔〕`像这些就没有包含在内，你可以在控制台尝试下。至于我并没有找到太好的方法。
你可以看维基百科 [标点符号](https://www.wikiwand.com/zh-hans/%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7 ) ，或者可以把所有的符号都加进去。
