### ISSUE TITLE
请问在Chrome中network中的那个SVG可以去掉吗？

### ISSUE THREAD

**Issue by qdchenyixuan** [waynecz/dadda-translate-crx#161]
照顾一下强迫症吧嘤嘤嘤

**Comment by waynecz** [comment]
![image](https://user-images.githubusercontent.com/11238540/51665856-a361f580-1ff7-11e9-9dd8-2dc7f6e1dba0.png)
这个吗？

**Comment by qdchenyixuan** [comment]
> ![image](https://user-images.githubusercontent.com/11238540/51665856-a361f580-1ff7-11e9-9dd8-2dc7f6e1dba0.png)
> 这个吗？

是的

**Comment by waynecz** [comment]
好像可以去掉哈哈哈，满足你

**Comment by qdchenyixuan** [comment]
多谢银酱~

**Comment by waynecz** [comment]
@qdchenyixuan emmm，失败了，即使转成行内的还是会产生一个请求

![image](https://user-images.githubusercontent.com/11238540/51813412-19fd3c80-22f1-11e9-9cca-0db0d1346e95.png)

**Comment by qdchenyixuan** [comment]
哈哈哈没关系的，最近这几天用着已经习惯了~

**Comment by waynecz** [comment]
那我就关咯😘
