### ISSUE TITLE
页面中单词选中不能读音

### ISSUE THREAD

**Issue by Lxjazni7** [waynecz/dadda-translate-crx#163]
页面中单词选中不能读音 点击了没有效果

**Comment by waynecz** [comment]
有两种情况：
1.  类似 github 或者 medium 之类的网站设置了 Content-Security-Policy, 不允许加载白名单之外的 host 的资源
2. 网络对搜狗不友好

你可以发下你碰到问题的网站出来我看下

**Comment by Lxjazni7** [comment]
那就是github的白名单问题了 谢谢
