### ISSUE TITLE
最新版本划词翻译乱码

### ISSUE THREAD

**Issue by Xiaolang0** [waynecz/dadda-translate-crx#165]
尝试过了卸载后重新安装，还是不行
版本是从chrome商店下载的最新的

**Comment by 00LT00** [comment]
我也是，就刚刚突然出现问题

**Comment by gzhou95** [comment]
Same... 突然就不能用了

**Comment by g-zhima** [comment]
同样的问题，看来不是个人原因。。

**Comment by Utaha** [comment]
Chromium 71.0.3578.98 同样问题

**Comment by belmino-shi** [comment]
同样问题

**Comment by linyu0219** [comment]
re

**Comment by strongcode9527** [comment]
是的，也有这个问题

**Comment by subcrew** [comment]
+1

**Comment by RickyWong33** [comment]
+1

**Comment by shinebay** [comment]
显示一堆杂乱字符串，比如“sT1cbGEhr2RkX2qBE”

**Comment by Ehco1996** [comment]
+1

**Comment by Ehco1996** [comment]
是翻译api被限制了？

**Comment by inu1255** [comment]
由于sogou升级导致
参见 https://github.com/waynecz/dadda-translate-crx/pull/166

**Comment by waynecz** [comment]
问题已由 @inu1255 修复，并且修复中主动去获取了导致问题产生的某个 seed，所以应该稳定了很多，感谢大佬。

修复版本：v1.2.0
