### ISSUE TITLE
Translate Error started from 2019/2/15

### ISSUE THREAD

**Issue by LRENZ** [waynecz/dadda-translate-crx#167]
![image](https://user-images.githubusercontent.com/19406202/52833152-844a1580-3116-11e9-8f15-a7a96459570c.png)

Perhaps some error occurs when parsed the response 

Here is my setting

![image](https://user-images.githubusercontent.com/19406202/52833334-3aadfa80-3117-11e9-8e4c-bd39e9f1c128.png)

**Comment by imvintagetyger** [comment]
删除，google商店重新下载

**Comment by waynecz** [comment]
可以尝试升级到 1.2.0 或者像 @imvintagetyger 说的直接删除重装，只要保证 1.2.0，就没问题

You can update to v1.2.0 or reinstall from chrome store as long as Dadda's version === v1.2.0, that's should be OK


![image](https://user-images.githubusercontent.com/11238540/52833603-7d240700-3118-11e9-86bb-dbfecdc4d26c.png)

**Comment by LRENZ** [comment]
Cool, it works

We can close this issue

Thanks for your efforts
