### ISSUE TITLE
Feature request: 收藏生词时同时收藏生词所在句子作为例句

### ISSUE THREAD

**Issue by Lxxyx** [waynecz/dadda-translate-crx#169]
相关 issue #22 

举例：

![image](https://user-images.githubusercontent.com/13161470/52902137-9d9eaf00-3247-11e9-81a0-cce6990c8180.png)

此处加入收藏的单词 dept，其句子为 “Some technical debt is in plain sight.”

则在生词本中的效果如下：

![image](https://user-images.githubusercontent.com/13161470/52902155-fbcb9200-3247-11e9-93bf-93876f27a86d.png)

如果例句可以同步至扇贝等平台则再好不过了，**因为单词带着上下文，对于部分同学而言（比如我）会是更有感觉的记忆方式**。

期待您的回复，谢谢创造出如此好用与好看的插件。

**Comment by waynecz** [comment]
建议很棒！用所在句子作为例句 技术上稍微有点困难，现在的想法是通过跳转到原文，然后高亮生词簿内单词的方法，另外「原文出处」可以点击单词卡片右上角的图标跳转。我再想想办法吧，还有就是最近没时间开发新功能😩。
