### ISSUE TITLE
为何有些单词不发音，无法全文翻译？

### ISSUE THREAD

**Issue by zhanghu0218** [waynecz/dadda-translate-crx#17]
无法全文翻译
![default](https://user-images.githubusercontent.com/37826977/38716260-55f4a75a-3f12-11e8-8547-8af0b18c3238.png)
这个翻译有问题吧？
![1](https://user-images.githubusercontent.com/37826977/38716335-c693890e-3f12-11e8-8cc7-00496acaa2e5.png)
有些单词无法发音
![1](https://user-images.githubusercontent.com/37826977/38716379-f7a371f8-3f12-11e8-8e6c-c331b79a7106.png)

**Comment by waynecz** [comment]
+ 全文翻译是指不能选择全文？

+ 因为大小写的原因，搜狗去翻译 More 了，这个单词可能有名字的意思，这应该是搜狗的短板

+ 无法发音是因为 github 禁止了外部音频。。暂时有点无解
