### ISSUE TITLE
deprecate npm modules

### ISSUE THREAD

**Issue by Vivapercuore** [waynecz/dadda-translate-crx#171]
deprecate css-loader@0.28.11 › cssnano@3.10.0 › postcss-merge-rules@2.1.2 › browserslist@^1.5.2 Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
deprecate eslint@4.19.1 › file-entry-cache@2.0.0 › flat-cache@1.3.4 › circular-json@^0.3.1 CircularJSON is in maintenance only, flatted is its successor.
deprecate webpack-cli@2.1.5 › jscodeshift@0.5.1 › nomnom@^1.8.1 Package no longer supported. Contact support@npmjs.com for more info.
deprecate webpack-cli@2.1.5 › jscodeshift@0.5.1 › babel-preset-es2015@^6.9.0 ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

so we can not run  npm i & build it from your code......even updated them

**Comment by waynecz** [comment]
Thanks for your suggestion! I'll upgrade them right away.
