### ISSUE TITLE
chrome插件翻译不能用了

### ISSUE THREAD

**Issue by liutaihua** [waynecz/dadda-translate-crx#173]
![image](https://user-images.githubusercontent.com/616461/53953213-b6470a00-410d-11e9-9701-4263af871eba.png)

os:  mac os 10.14.2 (18C54)
chrome: 版本 72.0.3626.119（正式版本） （64 位）

**Comment by waynecz** [comment]
插件的版本是？

**Comment by liutaihua** [comment]
@waynecz 
版本
1.1.22
谢谢

**Comment by waynecz** [comment]
升级到1.2.1就可以解决了:blush:
