### ISSUE TITLE
吐司弹词失效，没弹出过

### ISSUE THREAD

**Issue by justFI** [waynecz/dadda-translate-crx#176]
MBP Chrome 版本 73.0.3683.86（正式版本） （64 位）

已开启吐司弹词选项

**Comment by justFI** [comment]
以前有过一次，后来重新安装拓展就恢复了
但是又发生了，重新安装也没用了。。。

**Comment by jieekie** [comment]
不能用了，重装也不行，73.0.3683.103（正式版本） （64 位）
已开启吐司弹词选项

**Comment by elfgzp** [comment]
Same problem.

**Comment by noob9527** [comment]
+1
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
OS Version Ubuntu16.04

**Comment by Guo-XiPing** [comment]
+1
chrome 版本 73.0.3683.103（正式版本） （64 位）
windows 7 64bit
新安装，启动按键没有反应哎

**Comment by waynecz** [comment]
确实失效了，下版本（本周）修复

**Comment by nEdAy** [comment]
版本 74.0.3729.131（正式版本） （win 64 位）  正常

**Comment by moorejee** [comment]
弹窗失败与chrome的版本有关么？

**Comment by waynecz** [comment]
各位 1.2.4 已修复，这段时间不可用不好意思了
