### ISSUE TITLE
Feature request: 翻译图标弹出能不能可以通过按键前缀控制

### ISSUE THREAD

**Issue by kelly-apollo** [waynecz/dadda-translate-crx#18]
因为每次划词弹出图标有点干扰，如果插件支持修饰按键去控制弹出图标体验会很棒。
比如，我想划词翻译的时候要按 `⌘` + 划词才弹图标。

**Comment by waynecz** [comment]
[v1.1.0 已添加该功能](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.0)

**Comment by kelly-apollo** [comment]
@waynecz v1.10 实现的应该是 #37, #38 的 feature，使用快捷键触发翻译。

这个 issue 和 #33 说的是希望通过快捷键去控制蓝色小猫图标是出现。
