### ISSUE TITLE
有些网页没效果

### ISSUE THREAD

**Issue by zeyongTsai** [waynecz/dadda-translate-crx#180]
比如： `https://mobaxterm.mobatek.net/download-home-edition.html`

**Comment by waynecz** [comment]
可以提供下浏览器版本和插件版本吗，因为在我自己这里是正常的

![image](https://user-images.githubusercontent.com/11238540/56861372-74d32c80-69e3-11e9-9287-a3b13e576a37.png)

**Comment by zeyongTsai** [comment]
OS: win7
chrome:71.0.3578.98
plugin: 1.2.2

thanks

**Comment by saiksy** [comment]
我这里有些网站也是没有效果,比如https://os.phil-opp.com/paging-introduction/,我的是 macosx 10.14.4, chrome

**Comment by wxkuang** [comment]
Confirm this issue.

Can not open the popup box when double-click a word even if there's only *Dadda* is enabled.

* OS version: Manjaro KDE 5.15
* Browser version: Vivaldi 2.4.1488.40
* Dadda version: 1.2.2

There is no error message in console of developer tool.

**Comment by waynecz** [comment]
Hello，大家更新到 1.2.4 应该修复问题了
