### ISSUE TITLE
建议可以自动同步生词到扇贝单词

### ISSUE THREAD

**Issue by VincentGaoHJ** [waynecz/dadda-translate-crx#198]
现在是要将单词添加进生词本之后再点击同步到扇贝单词，是不是可以做一个选项，可以自动同步生词本中的所有单词到扇贝单词。

**Comment by waynecz** [comment]
可以再设置中开启这个

![image](https://user-images.githubusercontent.com/11238540/58445180-021eb380-813f-11e9-9c1e-4f77baf045e2.png)

**Comment by VincentGaoHJ** [comment]
嗯，已经开启，我以为这个开启之后还需要再在生词本里加入，疏忽了，谢谢~
