### ISSUE TITLE
吐司弹词, 不同单词弹词的时间间隔太短, 导致通知互相覆盖

### ISSUE THREAD

**Issue by ef6** [waynecz/dadda-translate-crx#21]
感谢作者

**Comment by waynecz** [comment]
@msongz @ef6  因为机子休眠后(比如合上盖子)计时器还在运行，但是弹窗不会弹出，导致了这个问题，目前没有很好的解决办法，有个方法是去生词簿里把单词去设置不同阶段

**Comment by msongz** [comment]
@waynecz 原来这样，或者一次出现数个同阶段单词这样呢

**Comment by waynecz** [comment]
我看看能不能改变下弹词方式，因为 chrome 的限制弹词其实限制挺多的
