### ISSUE TITLE
macOS系统通知栏疯狂推送通知

### ISSUE THREAD

**Issue by SUV97** [waynecz/dadda-translate-crx#211]
![Screen Shot 2019-07-04 at 18 19 12](https://user-images.githubusercontent.com/30253166/60659560-43b22500-9e88-11e9-929e-ef50671537f5.png)
## 系统信息
* 操作系统：macOS Mojave 10.14.5
* 浏览器：Google Chrome Canary 77.0.3842.0

**Comment by waynecz** [comment]
应该是电脑休眠后吐司仍在计时积压太久的缘故，目前可以选择关闭吐司

![image](https://user-images.githubusercontent.com/11238540/61839824-61e0d300-aed2-11e9-9ab0-f58d7d77cf3b.png)
