### ISSUE TITLE
生词提示显示可以有设置开关么？有点恼人

### ISSUE THREAD

**Issue by elephi** [waynecz/dadda-translate-crx#215]
![image](https://user-images.githubusercontent.com/1418703/61534956-e7730780-aa28-11e9-90ea-20ad6de81371.png)
如图，上面的提示时不时会弹出来，且没有地方关掉，有点恼人。

**Comment by waynecz** [comment]
设置页面中有关闭吐司的选项，另外吐司鼠标移上去应该是有关闭的选项的

![image](https://user-images.githubusercontent.com/11238540/61839849-76bd6680-aed2-11e9-9c1f-6ab4ca9f160b.png)

**Comment by elephi** [comment]
> 设置页面中有关闭吐司的选项，另外吐司鼠标移上去应该是有关闭的选项的
> 
> ![image](https://user-images.githubusercontent.com/11238540/61839849-76bd6680-aed2-11e9-9c1f-6ab4ca9f160b.png)

多谢，我试试！
