### ISSUE TITLE
Exception in webpage http://theme.typora.io/

### ISSUE THREAD

**Issue by hovenjay** [waynecz/dadda-translate-crx#218]
When I open the page [http://theme.typora.io/](http://theme.typora.io/) , an exception icon appears in the upper right corner of the page. As shown in the following figure:

![Snipaste_2019-08-23_11-31-55](https://user-images.githubusercontent.com/19848977/63565077-205b4a80-c59a-11e9-9c42-48b8d9bf6b2c.png)

My settings are as follows:

![Snipaste_2019-08-23_11-36-18](https://user-images.githubusercontent.com/19848977/63565111-3d901900-c59a-11e9-88e6-0827fca3726a.png)

**Comment by XuToTo** [comment]
while using **The Greater Suspender** extension, there is also a icon in some of suspended pages
![Screen Shot 2019-09-11 at 16 01 43](https://user-images.githubusercontent.com/8039013/64679301-0da7a780-d4ae-11e9-9a28-2b51228009a0.png)
