### ISSUE TITLE
Feature request: 收藏生词时同时收藏生词所在句子作为例句

### ISSUE THREAD

**Issue by ef6** [waynecz/dadda-translate-crx#22]
或者, 可以收藏句子, 同时选择句子中的一个单词加入到生词本

**Comment by waynecz** [comment]
这样交互上会有点麻烦，而且生词本内可以点击单词查看具体释义，你是指在弹词的时候弹出例句是吗？

**Comment by ef6** [comment]
我主要的目的是想背单词的时候复习一下当时我看见这个单词的语境
或者看见一个好句子想收藏背下来.

如果没有什么好办法的话,可以试着改进一下 **单词出处** 

想到了两个改进,
1. 高亮目标单词

2. 自动跳转到目标单词

**Comment by waynecz** [comment]
_(:зゝ∠)_ 抱歉有段时间没更新了，谢谢反馈，例句的话在生词簿里点击单词可以看到，高亮单词难以做到，因为页面内去查找单词会消耗很大的性能，暂时做不了
