### ISSUE TITLE
bug反馈 希望横向自动扩展，以看全文字

### ISSUE THREAD

**Issue by July12345** [waynecz/dadda-translate-crx#223]
当前版本，在遇到单词较长时如phonocardiogram 
![image](https://user-images.githubusercontent.com/43308130/64177613-77162d80-ce92-11e9-87e3-0265bd2f650a.png)
由于横向宽度固定? 内容显示不全，这一点在使用英英翻译时鼠标放置在英语句子内容时会在右上角显示对应单词中文词义，然而由于单词长度或者音标过长出现内容不能显示的问题

**Comment by waynecz** [comment]
v1.2.9 已修复 🤪
