### ISSUE TITLE
经常发生大流量的上传行为是什么情况？

### ISSUE THREAD

**Issue by track177** [waynecz/dadda-translate-crx#224]
插件是在谷歌网上有意思的下载的，今天发现上传流量显示chrome在持续上传（300多k每秒）打开chrome的任务管理器发现上传流量的是这个插件，每隔一会就又开始上传。每次几m的上传行为是在上传什么？

**Comment by track177** [comment]
刚刚才想起来，至少应该放张图，顺便看看是不是偶然事件，把插件重新打开，重启浏览器后插件未运行，随便选择个单词翻译后也没反应，然后就一直在上传（错误日志？）几分钟过去了还在上传。。
![dada.jpg](https://i.loli.net/2019/09/06/wbhojaTEMvgOZsR.jpg)

**Comment by LinEvil** [comment]
![image](https://user-images.githubusercontent.com/13027656/64368108-33672380-d04c-11e9-884b-dcd959a07089.png)
![image](https://user-images.githubusercontent.com/13027656/64368276-85a84480-d04c-11e9-93de-2bdfee6586e3.png)

已复现

**Comment by panda331** [comment]
不是偶然事件，我也发现了，昨晚看到上传很快以为是斗鱼，结果一看chrome的任务管理器发现是这扩展；就在刚才，上传达到2M/s，不得不停用

**Comment by waynecz** [comment]
感谢反馈！
** 在插件页面 [chrome://extensions](chrome://extensions) 可以查看插件的 background.js 来分析插件的网络行为 **

![image](https://user-images.githubusercontent.com/11238540/64392903-35ec6c00-d092-11e9-9784-121699db7e54.png)


打开吓了我一跳😂，应该是上个版本修复的时候的 Bug，导致 `logtrace` 和 `translate` 接口的无限循环调用，争取今天内修复吧，一个是获取搜狗token的请求，一个是翻译接口

![Kapture 2019-09-06 at 10 34 06](https://user-images.githubusercontent.com/11238540/64392866-0c334500-d092-11e9-960e-35343e87444d.gif)

相当于搜狗被我们 DDoS 了，_(:зゝ∠)_，对不起搜狗，大家能看到这条消息先暂时停用了吧

**Comment by cocobiz** [comment]
Same issue
CPU 也非常高

**Comment by waynecz** [comment]
修复版本 1.2.8 大概在一小时后过审可更新

**Comment by OptimisticQuan** [comment]
疯狂ddos搜狗，心疼搜狗
