### ISSUE TITLE
当所选文字中带加号 "+" 的时候翻译失败，在点击图标弹出来的翻译框中也无法翻译

### ISSUE THREAD

**Issue by 00LT00** [waynecz/dadda-translate-crx#230]
不知道是不是调用api的时候出现了问题，但是我直接在搜狗翻译网页的url中插入+的时候可以正确翻译，而且我感觉这个问题可能不止加号，大佬有空了可以看一看

**Comment by FatDoge** [comment]
还找到翻译不了的`Javascript 2D Perlin & Simplex noise functions`
初步估计是这种`+`和`&`是不是没转义传参导致的问题=-=

**Comment by waynecz** [comment]
v1.2.12 应该修复了

**Comment by FatDoge** [comment]
感谢！
