### ISSUE TITLE
請問怎麼關閉右鍵選單的達達達？

### ISSUE THREAD

**Issue by YuiTatsumi** [waynecz/dadda-translate-crx#233]
請問有選項可以關閉嗎？謝謝。
![2019-10-05_014458](https://user-images.githubusercontent.com/42616117/66228406-f1480500-e711-11e9-8c83-7f844c3d3390.png)

**Comment by Chorer** [comment]
同问。希望提供关闭右键菜单的选项。

**Comment by PraiseSunAsh** [comment]
emmmmm,这你可能要动下代码了，
进到/src/background.js里面，然后把277行的chrome.contextMenus.create函数块注释掉吧。。。

**Comment by waynecz** [comment]
我去弄个开关

**Comment by waynecz** [comment]
更新 1.2.9 后， 打开该选项并且重启浏览器就行了
![image](https://user-images.githubusercontent.com/11238540/66279202-b275a300-e8fb-11e9-9d3a-e2d73dcc6e9b.png)

**Comment by YuiTatsumi** [comment]
非常謝謝~ 感謝！
