### ISSUE TITLE
生词本 css 的问题

### ISSUE THREAD

**Issue by ef6** [waynecz/dadda-translate-crx#24]
![image](https://user-images.githubusercontent.com/17763501/38777007-1bf612ce-40d3-11e8-8753-7c9e18a0580a.png)

**Comment by msongz** [comment]
还有，生词本里的中文颜色比较灰，和白底一起，比较难看清楚

**Comment by waynecz** [comment]
[v1.0.1 已修复](https://github.com/waynecz/dadda-translate-crx/commit/deb2f96650f08b849bcb4089a5436e3a906c7713)
