### ISSUE TITLE
生词本收藏超过一定数量后, 生词本不显示后面收藏的单词, 且一直弹窗提醒, 无法斩词.

### ISSUE THREAD

**Issue by ef6** [waynecz/dadda-translate-crx#25]
![image](https://user-images.githubusercontent.com/17763501/38777035-af9b4a12-40d3-11e8-9d5b-adf4778a3bc4.png)

出现这种情况的单词, 弹窗显示的都是暂无翻译.

推测是生词本收藏数量达到上限了( 21个单词 ), 删除一些后可以再次收藏.

**Comment by theoneLee** [comment]
一样的情况。。我这边是收藏过21个后。后续的收藏没有在生词本里面显示。但是还是一直弹窗提示。

**Comment by waynecz** [comment]
[v1.0.1 已修复](https://github.com/waynecz/dadda-translate-crx/commit/deb2f96650f08b849bcb4089a5436e3a906c7713)
