### ISSUE TITLE
单词浮窗与popclip重叠

### ISSUE THREAD

**Issue by msongz** [waynecz/dadda-translate-crx#26]
popclip无法设置浮窗在高亮之下
所以
达达将来会否支持设置在下或在上显示吗？
![snipaste_2018-04-16_01-51-47](https://user-images.githubusercontent.com/2059694/38781493-c16dbde8-4118-11e8-8031-0a66fe1204ec.png)

**Comment by waynecz** [comment]
emmm，多个插件混用这个暂时不会有什么好办法，因为不知道其他插件有多顶层，设置一个很大很大的`z-index` 就是耍流氓了
