### ISSUE TITLE
该扩展程序未列在 Chrome 网上应用店中

### ISSUE THREAD

**Issue by Uetty** [waynecz/dadda-translate-crx#273]
被chrome浏览器禁了，用不了

**Comment by waynecz** [comment]
对的，以为权限原因，发了几次审核全挂了，正在更正中

**Comment by Uetty** [comment]
我通过自己打包可以安装，建议readme中贴出自己打包安装的方法

**Comment by Meng5in** [comment]
能发新版edge吗？

**Comment by Meng5in** [comment]
> 我通过自己打包可以安装，建议readme中贴出自己打包安装的方法

求个简单步骤……
我自己用edge自带的打包总是出问题，npm的crx又不太会用……
