### ISSUE TITLE
有些词没法加入生词本

### ISSUE THREAD

**Issue by DirtyBat** [waynecz/dadda-translate-crx#28]
比如“electoral”。
顺便就我个人而言我觉得划词后弹出的主子有点大.....
感谢这个插件让我淘汰了之前的湾湾划词翻译插件

**Comment by DirtyBat** [comment]
![image](https://user-images.githubusercontent.com/17296733/38871099-6f0cc150-4282-11e8-8b83-44c688a142a2.png)
顺便报个有趣的bug，233

**Comment by waynecz** [comment]
[v1.0.1 已修复](https://github.com/waynecz/dadda-translate-crx/commit/deb2f96650f08b849bcb4089a5436e3a906c7713)
