### ISSUE TITLE
麻烦哪位大哥发一下1.2.17的crx文件

### ISSUE THREAD

**Issue by Meng5in** [waynecz/dadda-translate-crx#281]
麻烦哪位大哥发一下1.2.17的crx文件，小白编译总是出错🙏🙏🙏

**Comment by waynecz** [comment]
你好，非常抱歉其实插件已经很长时间不维护了😂，目前应该处于不可用状态(外部不可访问搜狗新版 API)，1.2.17 也是，不过 crx 我还是先放一下你试试吧

[v1.2.17.crx.zip](https://github.com/waynecz/dadda-translate-crx/files/6021662/v1.2.17.crx.zip)

**Comment by Meng5in** [comment]
好的好的！谢谢！！！
