### ISSUE TITLE
[BUG反馈] 开启‘不翻译纯中文’后，没有过滤(中文)标点

### ISSUE THREAD

**Issue by zthxxx** [waynecz/dadda-translate-crx#34]
dadda version: 1.0.0

问题：开启 `不翻译纯中文` 开关后，选中的中文句子中包含标点字符的话，依然会显示翻译。

复现：嗯。。比如直接选中这句话。

期望行为：按照一般逻辑，这里 `不翻译纯中文` 应该表现为选中中文中不含英文或其他文字，就不出现翻译，但中文标签或英文标点，都应该算在被过滤的纯中文中。

**Comment by klzsysy** [comment]
+1

**Comment by yanshibin** [comment]
+1

**Comment by LiZhenNet** [comment]
+1

**Comment by waynecz** [comment]
[v1.0.1 已修复](https://github.com/waynecz/dadda-translate-crx/commit/deb2f96650f08b849bcb4089a5436e3a906c7713)
