### ISSUE TITLE
建议加入点击开启或关闭插件的功能

### ISSUE THREAD

**Issue by lkspc** [waynecz/dadda-translate-crx#35]
目前默认是一直打开的，在不想使用翻译的情况下，选中某词之后会弹出达达图标，很不友好。

建议加入鼠标点击图标开启插件或关闭插件的功能

**Comment by DirtyBat** [comment]
参考一下abp这些的“对当前网站启用与否”的选项就不错

**Comment by beanlee** [comment]
或者过3秒或几秒后，达达的图标可以自动隐藏

**Comment by zthxxx** [comment]
@lkspc 
我用的 1.0.0 版本，本身就带的有 `当前站点禁用`，
或者你可以试试这个插件管理：
https://chrome.google.com/webstore/detail/extension-manager/gjldcdngmdknpinoemndlidpcabkggco

**Comment by waynecz** [comment]
嗯嗯，更新至最新版本有当前网站禁用
