### ISSUE TITLE
能否添加个快捷键～

### ISSUE THREAD

**Issue by HQ-Lin** [waynecz/dadda-translate-crx#37]
由于工作中使用的是mac，经常是左手操作键盘，右手操作触摸板。
如果能将划词之后出现的小猫使用键盘快捷键形式触发我觉得效率会更高一些～
能否提供下呢？最好可提供自定义形式～

**Comment by kelly-apollo** [comment]
这个 issue 跟 #18 重复了

**Comment by waynecz** [comment]
#18
