### ISSUE TITLE
部分单词「暂无翻译」问题

### ISSUE THREAD

**Issue by kigawas** [waynecz/dadda-translate-crx#39]
![image](https://user-images.githubusercontent.com/4182346/39858774-87dda6de-5472-11e8-9efe-6e8b04c6ab28.png)

如图，弹出的单词中文内容很多是暂无翻译，收藏单词少的时候就有翻译（#25）

另，为啥这一个扩展里面同时用到了Vue和React 😮

**Comment by waynecz** [comment]
弹词现已不再显示中文释义（为了更适合背单词
