### ISSUE TITLE
样式类名做前缀或后缀处理。.show 这样的样式名太容易和网站里面的冲突

### ISSUE THREAD

**Issue by xiterjia** [waynecz/dadda-translate-crx#40]
如标题，希望修改一下样式名，作前缀或后缀的处理。
![image](https://user-images.githubusercontent.com/3360879/39965718-ef0ed0c0-56d0-11e8-85c2-0847a4ce3d1c.png)

**Comment by waynecz** [comment]
[已修复](https://github.com/waynecz/dadda-translate-crx/commit/deb2f96650f08b849bcb4089a5436e3a906c7713)
fixed #40
