### ISSUE TITLE
心想更新一下版本，单词本内容丢失了！

### ISSUE THREAD

**Issue by msongz** [waynecz/dadda-translate-crx#41]
建议在chrome商店或者扩展里着重提示一下

**Comment by waynecz** [comment]
丢失了吗！！！！！卧槽😭，对不起，我还特意写了段代码去兼容老数据，没想到是 bug 了。。。我去写着提示一下

**Comment by waynecz** [comment]
因为本地开发我不知道如何测试更新的情况，所以 GG 了

**Comment by waynecz** [comment]
你原来的单词量大吗

**Comment by msongz** [comment]
没关系，我是卸载了，再重新安装的，我以为是云同步喔

**Comment by waynecz** [comment]
哦哦，卸载了是会把数据清空掉，如果是从商店更新可能可以

**Comment by waynecz** [comment]
[1.1.0 更新啦](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.0), 这次更新还是蛮大的
