### ISSUE TITLE
几点功能建议

### ISSUE THREAD

**Issue by jasonhau1** [waynecz/dadda-translate-crx#43]
首先，这是是我见过的最漂亮的取词插件。
是否能增加这几个功能：
1，自动发音增加优先美音还是英音选项。
2，增加是否显示英文解释选项。
3， 可否增加only双击取词选项，有时候看文字喜欢大段划来划去，其实不是要翻译，因为开了自动翻译和发音，所以会自动跳出一大段中文以及自己念出来好长文字。

**Comment by waynecz** [comment]
十分感谢使用和建议！！关于这几点我解释下：

12 两点会考虑增加， 3 应该会以另外一种方式实现，比如划词后另外需要摁 ctrl 才会出来选项之类的

**Comment by waynecz** [comment]
[1.1.0更新](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.0) 优化了下你说的第三点，可以在划词后用 alt 控制显示翻译结果

**Comment by lixi0912** [comment]
建议增加下第一点的功能，有时候美音有时候英音还是比较困惑的，经常要自己在点下
