### ISSUE TITLE
每次打开浏览器都提醒更新，其实已经更新

### ISSUE THREAD

**Issue by BackTrackCRoot** [waynecz/dadda-translate-crx#47]
浏览器插件已经安装最新版，支持扇贝的哒哒了，但是每次开启浏览器都回提示 `V1.1.0大更新`的弹窗。
![1](https://user-images.githubusercontent.com/4964761/41071783-a1a0970a-6a2c-11e8-82bb-fbf8e34a3147.png)

**Comment by waynecz** [comment]
#45
