### ISSUE TITLE
此插件在页面插入的 div 影响了我网站的 css 排版

### ISSUE THREAD

**Issue by weaming** [waynecz/dadda-translate-crx#50]
`<div class="__transltor">`

**Comment by waynecz** [comment]
可以给下你的网站吗，我 debug 下，插件的样式应该都是有`__`开头的，应该不会影响你的样式

**Comment by weaming** [comment]
可能我没说清楚，你的div加了类，没错。

我的样式是针对所有 `div {}` 的

**Comment by waynecz** [comment]
那应该就是你网站的样式影响了插件的样式吧？最好给个网站或者截图或者代码看下。。。这样说我什么都做不了呀😂

**Comment by weaming** [comment]
没有网站，你可以模拟一下

**Comment by waynecz** [comment]
...因为没提供有用的信息，暂时关闭 issue 了

**Comment by weaming** [comment]
https://v.bitsflow.org/i50/

**Comment by weaming** [comment]
还是那两个问题

这个div是必需的吗？
这个div可以隐藏吗？  `display: none`

**Comment by waynecz** [comment]
必需，不可隐藏。但插件可以做成禁用情况下删掉 div

**Comment by weaming** [comment]
这个是模板div吗，是的话，可以 copy 了之后再显示

**Comment by waynecz** [comment]
我修改下，下个版本实现黑名单内不插入 div ，copy 后显示改的地方会有点多

**Comment by waynecz** [comment]
新版本修复了
