### ISSUE TITLE
新版本生词本中点击单词无反应

### ISSUE THREAD

**Issue by chlins** [waynecz/dadda-translate-crx#52]
![image](https://user-images.githubusercontent.com/31262637/41213000-d5de7bd6-6d74-11e8-9bd9-d3a44e6d7781.png)
点击后变成不可选状态

**Comment by waynecz** [comment]
我这边是正常的，可以发个动图看看么？

**Comment by chlins** [comment]
![qq20180611-173405-hd](https://user-images.githubusercontent.com/31262637/41223952-c760158c-6d9d-11e8-9e83-d139531d7a91.gif)

**Comment by waynecz** [comment]
咦，好奇怪，你的 Chrome 版本是多少

**Comment by waynecz** [comment]
控制台有报错信息吗？

**Comment by chlins** [comment]
chrome 版本66，控制台没有报错

**Comment by chlins** [comment]
环境mac 10.13
