### ISSUE TITLE
启用插件影响了CSDN的英文显示

### ISSUE THREAD

**Issue by CescMessi** [waynecz/dadda-translate-crx#54]
CSDN标题中的英文会被隐藏

**Comment by waynecz** [comment]
可以给个示例的网址吗？

**Comment by CescMessi** [comment]
[https://blog.csdn.net/Augusdi/article/details/9020395](url)
标题前面的OpenCV可以选中复制，但是就是不显示。下面的相关文章里面的英文也是同样的情况。

**Comment by CescMessi** [comment]
这个情况是在win7的电脑上出现的，win10电脑无此问题

**Comment by waynecz** [comment]
😂 我这边暂时没法复现，有截图么，还有 win7上的 chrome 是什么版本的

**Comment by CescMessi** [comment]
![image](https://user-images.githubusercontent.com/15847281/41717155-5e75fece-758b-11e8-932d-7741e4f47e5d.png)
版本 67.0.3396.87

**Comment by waynecz** [comment]
尴尬，关错了。。。

**Comment by blacklisten** [comment]
win7  会出现  谷歌是最新版本

**Comment by waynecz** [comment]
v1.1.6 应该已经修复了
