### ISSUE TITLE
功能请求 1快速关闭吐司 2搜索失败后自动重试

### ISSUE THREAD

**Issue by Aaron-Bird** [waynecz/dadda-translate-crx#55]
1 快速关闭吐司
有时会同时弹出多个吐司, 遮挡屏幕右侧,影响操作.
可以添加一个"批量关闭吐司"的选项,快速清除所有吐司.
![close_all_toast](https://user-images.githubusercontent.com/25508292/41707566-f4a21b96-7570-11e8-9f19-c4ae47de4d4b.gif)
2 自动重试
达达用的api似乎无法查询首字母大写的单词
![try_before](https://user-images.githubusercontent.com/25508292/41707818-95ee2576-7571-11e8-9668-c60844df60f1.PNG)
当单词查询失败且首字母为大写字母时,自动将该单词转小写后重新搜索.
![try](https://user-images.githubusercontent.com/25508292/41707828-9bac5a14-7571-11e8-9eaf-a0820c905723.PNG)

我已经实现了这两个功能
https://github.com/Aaron-Bird/dadda-translate-crx/tree/feature
如果您觉得可行, 我会申请Pull requests

**Comment by waynecz** [comment]
非常完美！！快提 PR 吧！！批量关闭可以默认开启
