### ISSUE TITLE
建议增加翻译快捷键

### ISSUE THREAD

**Issue by woncode** [waynecz/dadda-translate-crx#58]
能否像[划词翻译](https://github.com/Selection-Translator/crx-selection-translate)一样，可以设定一个快捷键，划词以后不出现达达翻译图标，而是按了快捷键后直接弹出翻译窗口。

现在的设定每次划词都会出现达达图标，但是很多时候划词并不是为了翻译（复制、剪切···），我希望只有选择了想要翻译的词后，按下快捷键，才激活翻译，直接弹出翻译悬浮窗口，否则什么事都不要做。

谢谢！

**Comment by waynecz** [comment]
![image](https://user-images.githubusercontent.com/11238540/41827586-c9e7e404-7862-11e8-9a7e-8047701d959c.png)
开启这两个选项可以实现

**Comment by woncode** [comment]
确实可以，感谢回复

**Comment by Fisher-Joe** [comment]
为什么我设置后还是划词后直接出现了结果？
