### ISSUE TITLE
BUG: 启用插件后，网页加粗字体无法显示

### ISSUE THREAD

**Issue by shinebay** [waynecz/dadda-translate-crx#63]
已经确定是达达的问题，加粗字体不能显示，完全空白

**Comment by waynecz** [comment]
请问是win7下吗？

**Comment by shinebay** [comment]
@waynecz 对

**Comment by waynecz** [comment]
:cry:我这边暂时没法排查，你那可以截图让我看下消失的字体的css吗

**Comment by shinebay** [comment]
@waynecz 对于同时满足font-family: "Roboto"; font-weight:"bold"的字体全都没法显示，撤销任何一个条件都能正常显示，我本机安装有Roboto字体

**Comment by shinebay** [comment]
@waynecz 对于其他特定字体，即使不加粗，也有可能出现不能显示的bug，比如[https://free.com.tw/](https://free.com.tw/) ，里面的标题全都变成空白了，font-family为jf-jinxuan，只要一关闭达达翻译，马上就能显现文字了，不知道是什么情况
达达翻译版本：1.1.5；chrome为最新版本：版本 67.0.3396.99（正式版本） （64 位）

**Comment by waynecz** [comment]
谢谢反馈！！我尽快修复下！
