### ISSUE TITLE
鼠标悬停的时候，显示的是哈哈哈

### ISSUE THREAD

**Issue by jyq920203** [waynecz/dadda-translate-crx#71]
鼠标悬停的时候，显示的是哈哈哈

**Comment by waynecz** [comment]
emm，可以说的具体点吗

**Comment by jyq920203** [comment]
![悬停](https://user-images.githubusercontent.com/9977948/43197651-67aa3528-903e-11e8-87fb-c8697a6f8982.png)

**Comment by waynecz** [comment]
哦哦，哈哈哈，没注意，谢谢反馈，我改一下！

**Comment by tt-leader** [comment]
啊? 我还以为这是故意设为"哈哈哈"的

**Comment by woodpenker** [comment]
我也以为是故意的....
