### ISSUE TITLE
希望添加是否显示悬浮窗的设置项

### ISSUE THREAD

**Issue by Dark-Existed** [waynecz/dadda-translate-crx#72]
希望能够自由设置是否显示悬浮窗
个人阅读的时候有用鼠标划词的习惯  浮窗就一直出现
个人理想的使用场景是：
不显示浮窗  设置成按alt 进行翻译 划词后就不会一直出现悬浮窗

**Comment by waynecz** [comment]
可以试下开始 直接翻译 选项😋

**Comment by waynecz** [comment]
加上alt 控制

**Comment by Dark-Existed** [comment]
发现新大陆  谢谢！

**Comment by waynecz** [comment]
应该是我命名不恰当造成的，对于这个选项可有更合适的命名？
