### ISSUE TITLE
控件的显示层次是不是有点问题

### ISSUE THREAD

**Issue by tt-leader** [waynecz/dadda-translate-crx#77]
如下图所示, 在[tensorflow](https://www.tensorflow.org/performance/xla/jit)网页上, 翻译控件的显示会被右边栏给遮住, 不知道是哪里出现了问题

![screenshot from 2018-07-27 15-15-42](https://user-images.githubusercontent.com/7656532/43307126-f97a0f7e-91af-11e8-87b7-513281db18a7.png)

**Comment by waynecz** [comment]
感谢反馈！已发现原因，下版本修复❤️

**Comment by huiyifyj** [comment]
是z-index属性没默认侧边栏高？
