### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 13ruceYu** [waynecz/dadda-translate-crx#78]
打开程序搜词的时候是否可以展示详细释义，并且添加到生词表的选项呢？

**Comment by waynecz** [comment]
是指这里吗
<br>
![image](https://user-images.githubusercontent.com/11238540/43329751-e40cb666-91f3-11e8-91ba-de2942a0446e.png)

**Comment by Lemon1Tea** [comment]
加油哈，很是喜欢这款Extension！

**Comment by waynecz** [comment]
预计在 1.2.0 里加上😋

**Comment by ifyour** [comment]
太好用了, 感谢作者, 可以提供一个赞助二维码, 支持一下!

**Comment by waynecz** [comment]
@ifyour 哈哈哈哈谢谢啦，有人喜欢就好，二维码就不了，看到有 issue 就是很大支持了🤪

**Comment by waynecz** [comment]
[1.1.10](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.10) 新增的页面内呼出输入框应该暂时可以替代这个需求了，2.0 后续将加强这个输入框
