### ISSUE TITLE
点击发音没反应

### ISSUE THREAD

**Issue by SidKwok** [waynecz/dadda-translate-crx#80]
会不会有可能是网络问题？

macOS 10.14 Beta 

chrome 68.0.3440.75

**Comment by waynecz** [comment]
请问是所有网站都这样吗？有一个可能是类似于 gihtub 对音频资源进行了CSP 限制，所以是放不出来的

**Comment by SidKwok** [comment]
噢噢 还真是github的问题，顺带一赞，好插件啊！

**Comment by waynecz** [comment]
谢谢鼓励！😋
