### ISSUE TITLE
希望能有读音功能

### ISSUE THREAD

**Issue by HenryDong123** [waynecz/dadda-translate-crx#85]
朗读+音标，或者只有音标也行呀

**Comment by BenjaminGao** [comment]
![snipaste_2018-08-02_08-39-14](https://user-images.githubusercontent.com/16028320/43555922-a0d191b0-962f-11e8-8cd9-0e112fe8fbc2.png)

音标有，点击音标就发音

**Comment by waynecz** [comment]
某些网站例如 github 设置了 Content Security policy(内容安全政策), 一些外部资源(音频等）不能被加载，就没办法播放了

**Comment by HenryDong123** [comment]
好的，谢谢你们
