### ISSUE TITLE
希望按下一个按钮后就开启划词翻译, 再按一下就关闭, 而不是每次划词都需要按Alt

### ISSUE THREAD

**Issue by hd5970** [waynecz/dadda-translate-crx#86]
希望能够开开关划词添加一个快捷方式, 比如我在阅读英文网页, 需要划词, 但是不想每次按alt.

感谢开发者提供如此优秀的插件

**Comment by Aaron-Bird** [comment]
不知道这种是不是你要的?
在上边加个按钮,可以快速关闭扩展
![power](https://user-images.githubusercontent.com/25508292/43540085-4c09192c-95f9-11e8-8236-b56c545390c0.gif)

**Comment by waynecz** [comment]
是指开启后，划词直接弹出翻译吗，关闭就需要摁 alt(假如你开启了 alt 控制)

**Comment by hd5970** [comment]
在中文网页, 是不需要划词的, 但是我又忍不住鼠标划出我正在阅读的部分, 所以划词不能一直打开.

在英文网页, 频繁需要划词, 但是每次按alt就很麻烦

现在是否打开划词, 需要到插件设置中用鼠标点击选择, 希望能有一个快捷键, 不用跑到设置里, 按一下就能打开/关闭划词.

**Comment by hd5970** [comment]
<img width="352" alt="qq20180802-110635 2x" src="https://user-images.githubusercontent.com/7328372/43560251-23c8da60-9644-11e8-8ec1-2ec55263e766.png">
其实就是, 这个开关能够配置一个快捷键, 然后不用跑到设置里, 直接在页面上按下快捷键就可以打开/关闭

**Comment by Aaron-Bird** [comment]
这样?
![power](https://user-images.githubusercontent.com/25508292/43570237-65e7d5b8-966c-11e8-9cea-3e1621028cea.gif)

**Comment by waynecz** [comment]
@Aaron-Bird 你实在是太棒了！！哈哈哈哈，看起来离楼主的意思就是差个快捷键了，等你的 PR 哟🤩

**Comment by Aaron-Bird** [comment]
@waynecz
还是您来写吧,我就不提交PR了
那个按钮照理说为了美观应该用图标,但您的图标好象是统一放在iconfont.ttf里,我不会改这个
而且当初写的时候打算自己用, 动了部分不该动的代码
https://github.com/Aaron-Bird/dadda-translate-crx/commit/6aa1cd62d54b47f093aecfec3cb5cc84e6b7b08e

**Comment by waynecz** [comment]
[V1.1.10](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.1.10) 新增按三下 `alt` 健快捷控制是否直接显示翻译结果，建议同时开启 alt 键控制，这样就可以随意切换可
