### ISSUE TITLE
对错误的单词进行错误的翻译

### ISSUE THREAD

**Issue by sufanx** [waynecz/dadda-translate-crx#97]
错误的单词（并没有这个单词）：Transation
被翻译为：交易（应该是Transaction）
截图见下
[![i95sq1.png](https://s1.ax1x.com/2018/09/06/i95sq1.png)](https://imgchr.com/i/i95sq1)

**Comment by waynecz** [comment]
这估计是翻译引擎的模糊纠正了，事实上不同翻译引擎对不存在但形似的单词都会有自己的做法，我截了几个主流的引擎对 `Transation ` 的翻译，可以看到只有谷歌是不进行翻译。（现在在做的 2.0 版本正在添加对谷歌的支持）😝

### 有道：
![image](https://user-images.githubusercontent.com/11238540/45132601-1d6a1d00-b1c4-11e8-9f14-8c5a1bb7de6e.png)

### 百度：
![image](https://user-images.githubusercontent.com/11238540/45132661-5aceaa80-b1c4-11e8-8e8a-1bfd4da03fdb.png)

### 剑桥：
![image](https://user-images.githubusercontent.com/11238540/45132672-64f0a900-b1c4-11e8-8189-22270736445a.png)

### 谷歌：
![image](https://user-images.githubusercontent.com/11238540/45132678-6ae68a00-b1c4-11e8-89b7-8a124324d761.png)

**Comment by sufanx** [comment]
我发觉了，只是在想有没有办法“纠正“一下，还是谷歌大大好呀，其他的纠正就纠正吧，翻译之后也一起纠正了呀，让人迷惑

**Comment by waynecz** [comment]
嗯嗯，其实也很难说孰优孰劣，英语文章里错别字什么的任何作者也可能都会犯，所以引擎对应的行为也算是引擎的 “功能” 了，只能看我们自己的喜好挑选引擎了。（But！我个人还是很喜欢搜狗对长句和段落的翻译还原度的😉

**Comment by sufanx** [comment]
加油👍
